package com.jeremy.model;
// Generated 31 mai 2019 17:12:34 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classe generated by hbm2java
 */
@Entity
@Table(name = "classe", catalog = "new_project")
public class Classe implements java.io.Serializable {

	private int codeClasse;
	private Professeur professeur;
	private String nomClasse;
	private Set<Professeur> professeurs = new HashSet<Professeur>(0);
	private Set<Enseigner> enseigners = new HashSet<Enseigner>(0);
	private Set<Eleve> eleves = new HashSet<Eleve>(0);

	public Classe() {
	}

	public Classe(int codeClasse, Professeur professeur) {
		this.codeClasse = codeClasse;
		this.professeur = professeur;
	}

	public Classe(int codeClasse, Professeur professeur, String nomClasse, Set<Professeur> professeurs,
			Set<Enseigner> enseigners, Set<Eleve> eleves) {
		this.codeClasse = codeClasse;
		this.professeur = professeur;
		this.nomClasse = nomClasse;
		this.professeurs = professeurs;
		this.enseigners = enseigners;
		this.eleves = eleves;
	}

	@Id

	@Column(name = "CODE_CLASSE", unique = true, nullable = false)
	public int getCodeClasse() {
		return this.codeClasse;
	}

	public void setCodeClasse(int codeClasse) {
		this.codeClasse = codeClasse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NUM_PROF", nullable = false)
	public Professeur getProfesseur() {
		return this.professeur;
	}

	public void setProfesseur(Professeur professeur) {
		this.professeur = professeur;
	}

	@Column(name = "NOM_CLASSE", length = 20)
	public String getNomClasse() {
		return this.nomClasse;
	}

	public void setNomClasse(String nomClasse) {
		this.nomClasse = nomClasse;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classe")
	public Set<Professeur> getProfesseurs() {
		return this.professeurs;
	}

	public void setProfesseurs(Set<Professeur> professeurs) {
		this.professeurs = professeurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classe")
	public Set<Enseigner> getEnseigners() {
		return this.enseigners;
	}

	public void setEnseigners(Set<Enseigner> enseigners) {
		this.enseigners = enseigners;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classe")
	public Set<Eleve> getEleves() {
		return this.eleves;
	}

	public void setEleves(Set<Eleve> eleves) {
		this.eleves = eleves;
	}

}
