package com.jeremy.model;
// Generated 31 mai 2019 17:12:34 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Matiere generated by hbm2java
 */
@Entity
@Table(name = "matiere", catalog = "new_project")
public class Matiere implements java.io.Serializable {

	private String codeMatiere;
	private String libelleMatiere;
	private Set<Enseigner> enseigners = new HashSet<Enseigner>(0);

	public Matiere() {
	}

	public Matiere(String codeMatiere) {
		this.codeMatiere = codeMatiere;
	}

	public Matiere(String codeMatiere, String libelleMatiere, Set<Enseigner> enseigners) {
		this.codeMatiere = codeMatiere;
		this.libelleMatiere = libelleMatiere;
		this.enseigners = enseigners;
	}

	@Id

	@Column(name = "CODE_MATIERE", unique = true, nullable = false, length = 5)
	public String getCodeMatiere() {
		return this.codeMatiere;
	}

	public void setCodeMatiere(String codeMatiere) {
		this.codeMatiere = codeMatiere;
	}

	@Column(name = "LIBELLE_MATIERE", length = 20)
	public String getLibelleMatiere() {
		return this.libelleMatiere;
	}

	public void setLibelleMatiere(String libelleMatiere) {
		this.libelleMatiere = libelleMatiere.toUpperCase();
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "matiere")
	public Set<Enseigner> getEnseigners() {
		return this.enseigners;
	}

	public void setEnseigners(Set<Enseigner> enseigners) {
		this.enseigners = enseigners;
	}

}
