package com.jeremy.model;
// Generated 31 mai 2019 17:12:34 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Professeur generated by hbm2java
 */
@Entity
@Table(name = "professeur", catalog = "new_project")
public class Professeur implements java.io.Serializable {

	private String numProf;
	private Classe classe;
	private String nomProf;
	private String prenomProf;
	private String telProf;
	private Set<Enseigner> enseigners = new HashSet<Enseigner>(0);
	private Set<Classe> classes = new HashSet<Classe>(0);

	public Professeur() {
	}

	public Professeur(String numProf) {
		this.numProf = numProf;
	}

	public Professeur(String numProf, Classe classe, String nomProf, String prenomProf, String telProf,
			Set<Enseigner> enseigners, Set<Classe> classes) {
		this.numProf = numProf;
		this.classe = classe;
		this.nomProf = nomProf;
		this.prenomProf = prenomProf;
		this.telProf = telProf;
		this.enseigners = enseigners;
		this.classes = classes;
	}

	@Id

	@Column(name = "NUM_PROF", unique = true, nullable = false, length = 10)
	public String getNumProf() {
		return this.numProf;
	}

	public void setNumProf(String numProf) {
		this.numProf = numProf;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_CLASSE")
	public Classe getClasse() {
		return this.classe;
	}

	public void setClasse(Classe classe) {
		this.classe = classe;
	}

	@Column(name = "NOM_PROF", length = 50)
	public String getNomProf() {
		return this.nomProf;
	}

	public void setNomProf(String nomProf) {
		this.nomProf = nomProf.toUpperCase();
	}

	@Column(name = "PRENOM_PROF", length = 50)
	public String getPrenomProf() {
		return this.prenomProf;
	}

	public void setPrenomProf(String prenomProf) {
		this.prenomProf = prenomProf.toUpperCase();
	}

	@Column(name = "TEL_PROF", length = 12)
	public String getTelProf() {
		return this.telProf;
	}

	public void setTelProf(String telProf) {
		this.telProf = telProf;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "professeur")
	public Set<Enseigner> getEnseigners() {
		return this.enseigners;
	}

	public void setEnseigners(Set<Enseigner> enseigners) {
		this.enseigners = enseigners;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "professeur")
	public Set<Classe> getClasses() {
		return this.classes;
	}

	public void setClasses(Set<Classe> classes) {
		this.classes = classes;
	}

}
